"""From recorded bytes to a session summary, through the real commands.

Every test here replays one of E01's captured Claude Code sessions over HTTP into a
real receiver and a real store, runs the activity reducer, then invokes `telltale`.
Nothing is stubbed and nothing calls a reducer's internals: what is asserted is what a
person running the command would see.

The goldens are `fixtures/golden/claude/<scenario>/{show.json,timeline.txt}`, and they
are the output of `telltale show` and `telltale timeline` on exactly this pipeline.
They are regenerated by running this suite with TELLTALE_GOLDEN=write, the same code
path as the comparison, so no golden can come from a route the test does not take.
Every number in them is checked by hand against the fixture in docs/log/W1-T2.md.

One normalization, named. `reducer_version` is the hash of the reducer's own source,
so it changes with every edit to it and would make the goldens a diff of themselves; it
is replaced by a placeholder. Nothing else is touched: the capture
id, the timestamps, the token counts and the row order are compared byte for byte,
which is what makes a golden worth having.

Why these three scenarios. S1 is the shape the product exists for: a failing test, an
edit, a passing test. S4 is the only capture with a subagent, which is the one place
where token attribution can double-count. S7 is the only capture with compaction, and it
compacted four times on three surfaces with one failure, which is where the correlation
rules earn their keep.
"""

from __future__ import annotations

import json
import os
from pathlib import Path
from typing import TYPE_CHECKING, Any

import pytest
from conftest import CODEX_FIXTURES, activity_fields, launched, telltale_cli

from telltale import cli, measures

if TYPE_CHECKING:
    from collections.abc import Callable, Iterable, Mapping, Sequence

    from conftest import Replayed

    from telltale.store import Store

GOLDEN = Path(__file__).resolve().parents[2] / "fixtures" / "golden"
SCENARIOS = ("S1", "S4", "S7")

# The Codex sessions, chosen the same way. E02's S1 is the same failing-test shape as
# E01's; S3 is the one that read the credential file and the smallest capture with a
# tool call, so its goldens are readable end to end; S6 is the only capture that edited
# a file and committed, which is where a file_edit and an exit code have to survive.
CODEX_SCENARIOS = ("S1", "S3", "S6")

# One list rather than two suites: the pipeline is the same one, and a provider that
# reduces to almost nothing is exactly what this catches.
# The five activity types design 6.10 gives one tool call each. Named here so that the
# assertion below counts every one of them and cannot pass by a call falling into a
# type it forgot to look at.
TOOL_KINDS = ("command", "verification_run", "file_read", "file_edit", "tool_call")

CASES = [("claude", name) for name in SCENARIOS] + [
    ("codex", name) for name in CODEX_SCENARIOS
]

# The reducer version is a hash of the source, so it is different in every commit that
# touches activities.py. The goldens carry this instead, and the test that a version is
# recorded at all is `test_show_matches_golden` failing when the key disappears.
STRIPPED = "<reducer_version>"

# Set to "write" to regenerate the goldens instead of comparing against them. The
# comparison and the regeneration share this one function, so a golden is always the
# output of the command the test runs.
WRITE = os.environ.get("TELLTALE_GOLDEN") == "write"


def _reduce(
    replay: Callable[..., Replayed],
    store: Store,
    settled: Callable[[Store], Store],
    scenario: str,
    provider: str = "claude",
) -> str:
    """Replay one scenario, run every reducer, close the store, return the capture id.

    The close is the barrier: `Store._serve_once` takes a job off the queue before it
    opens the transaction, so an empty queue is not proof that the writer has finished
    (conftest's `settled` says why at length). Reading before it would ask the question
    of fewer rows than were written.
    """
    replayed = replay(scenario, provider=provider)
    store.rebuild(replayed.capture)
    settled(store)
    return replayed.capture


def _golden(path: Path, actual: str) -> None:
    if WRITE:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(actual, encoding="utf-8")
    assert path.exists(), f"{path} is missing; regenerate with TELLTALE_GOLDEN=write"
    assert actual == path.read_text(encoding="utf-8")


def _run(capsys: pytest.CaptureFixture[str], argv: Sequence[str]) -> str:
    assert cli.main(list(argv)) == 0
    return capsys.readouterr().out


def _stripped(printed: str) -> str:
    summary = json.loads(printed)
    assert summary["reducer_version"].startswith("act-"), summary["reducer_version"]
    summary["reducer_version"] = STRIPPED
    return json.dumps(summary, indent=2, ensure_ascii=False) + "\n"


def _rows(store: Store, capture: str) -> list[tuple[Any, ...]]:
    """Activity and evidence rows as comparable tuples, ids and all."""
    tables = (store.activities(capture), store.evidence(capture))
    return [_row(row) for table in tables for row in table]


def _row(row: Mapping[str, Any]) -> tuple[Any, ...]:
    return tuple(
        (key, json.dumps(value, sort_keys=True)) for key, value in sorted(row.items())
    )


def _referenced(store: Store, capture: str) -> Iterable[tuple[str, str]]:
    """Every id this capture's derived rows point at, with where it was found."""
    for row in store.activities(capture):
        for name, ids in dict(row["provenance"]).items():
            for one in ids:
                yield f"{row['activity_id']}.provenance.{name}", one
        for one in dict(row["fields"]).get("delegated_tool_calls") or []:
            yield f"{row['activity_id']}.delegated_tool_calls", one
    for row in store.evidence(capture):
        for one in row["source"]:
            yield f"{row['evidence_id']}.source", one


@pytest.mark.integration
@pytest.mark.parametrize(("provider", "scenario"), CASES)
def test_show_matches_golden(
    provider: str,
    scenario: str,
    replay: Callable[..., Replayed],
    store: Store,
    settled: Callable[[Store], Store],
    capsys: pytest.CaptureFixture[str],
) -> None:
    """`telltale show` prints Appendix B, coverage first and the diagnostics last."""
    capture = _reduce(replay, store, settled, scenario, provider)
    printed = _stripped(_run(capsys, ["show", capture]))
    keys = list(json.loads(printed))
    assert keys[0] == "coverage", keys
    assert keys[-1] == "diagnostics", keys
    _golden(GOLDEN / provider / scenario / "show.json", printed)


@pytest.mark.integration
@pytest.mark.parametrize(("provider", "scenario"), CASES)
def test_timeline_matches_golden(
    provider: str,
    scenario: str,
    replay: Callable[..., Replayed],
    store: Store,
    settled: Callable[[Store], Store],
    capsys: pytest.CaptureFixture[str],
) -> None:
    """`telltale timeline` prints one row per activity, in the order they started."""
    capture = _reduce(replay, store, settled, scenario, provider)
    printed = _run(capsys, ["timeline", capture])
    _golden(GOLDEN / provider / scenario / "timeline.txt", printed)


@pytest.mark.integration
@pytest.mark.parametrize(("provider", "scenario"), CASES)
def test_rebuild_is_repeatable(
    provider: str,
    scenario: str,
    replay: Callable[..., Replayed],
    store: Store,
    settled: Callable[[Store], Store],
) -> None:
    """Two rebuilds of one capture produce byte-identical activity and evidence rows.

    Break it by giving an activity a `ulid()` id or an Evidence a wall-clock
    `created_at` and this fails on every row, which is the point: a derived table that
    changes when nothing changed cannot be compared across captures or across time.
    """
    replayed = replay(scenario, provider=provider)
    store.rebuild(replayed.capture)
    before = _rows(store, replayed.capture)
    store.rebuild(replayed.capture)
    settled(store)
    after = _rows(store, replayed.capture)
    assert before, "the reducer wrote nothing at all"
    assert before == after


@pytest.mark.integration
@pytest.mark.parametrize(("provider", "scenario"), CASES)
def test_every_source_and_provenance_id_resolves(
    provider: str,
    scenario: str,
    replay: Callable[..., Replayed],
    store: Store,
    settled: Callable[[Store], Store],
) -> None:
    """No derived row points at an id that is not in this capture.

    An unresolvable id is the failure mode `explain` cannot report around: the chain
    from a number to the bytes behind it is only as good as its weakest link, and a
    reducer that invents an id breaks it silently.
    """
    capture = _reduce(replay, store, settled, scenario, provider)
    known = {str(row["observation_id"]) for row in store.observations(capture)}
    known |= {str(row["activity_id"]) for row in store.activities(capture)}
    seen = _referenced(store, capture)
    dangling = [(where, one) for where, one in seen if one not in known]
    assert not dangling, dangling
    assert known, "no observations were stored"


@pytest.mark.integration
def test_s7_compactions_carry_pre_and_post_tokens_on_three_surfaces(
    replay: Callable[..., Replayed],
    store: Store,
    settled: Callable[[Store], Store],
) -> None:
    """S7 compacted four times. Three succeeded, and all three were seen three ways.

    The fourth is the one that matters most: E01 measured a compaction that failed with
    `too_few_groups` and reported no post_tokens and no stream boundary, so the summary
    reports partial coverage for post_compaction_tokens rather than a smaller total that
    looks complete.
    """
    capture = _reduce(replay, store, settled, "S7")
    found = activity_fields(store, capture, "compaction")
    rows = sorted(found, key=lambda one: int(one["compaction_index"]))
    assert [row["pre_tokens"] for row in rows] == [34181, 35113, 38398, 42366]
    assert [row.get("post_tokens") for row in rows] == [None, 3909, 8138, 5193]
    assert [row["success"] for row in rows] == [False, True, True, True]
    assert rows[0]["surfaces"] == ["hook", "otel_logs"]
    for row in rows[1:]:
        assert row["surfaces"] == ["hook", "otel_logs", "stream"]
    summary = measures.summary(store, capture)
    assert summary["context"]["compactions"] == 4
    assert summary["context"]["pre_compaction_tokens"] == 34181 + 35113 + 38398 + 42366
    assert summary["context"]["post_compaction_tokens"] == 3909 + 8138 + 5193
    assert summary["warnings"]["post_compaction_tokens"]


@pytest.mark.integration
def test_s4_subagent_has_attributed_tokens(
    replay: Callable[..., Replayed],
    store: Store,
    settled: Callable[[Store], Store],
) -> None:
    """S4 delegated once, and the child's tokens are attributed without being doubled.

    `attributed_total_tokens` is the sum over the five api_requests whose query_source
    names this agent, and those five are already inside the capture's own usage totals.
    `provider_total_tokens` is what claude_code.subagent_completed reports, and the two
    are 92479 and 20093: different quantities, so they are stored under different names
    and neither is added to the other (spec 13.6).
    """
    capture = _reduce(replay, store, settled, "S4")
    rows = activity_fields(store, capture, "subagent")
    assert len(rows) == 1
    child = rows[0]
    assert child["agent_id"] == "a98af9d1d9cc27170"
    assert child["agent_type"] == "Explore"
    assert child["attributed_requests"] == 5
    assert child["attributed_total_tokens"] == 92479
    assert child["provider_total_tokens"] == 20093
    assert len(child["delegated_tool_calls"]) == 4
    # The capture's own totals count every request once, subagent requests included.
    summary = measures.summary(store, capture)
    assert summary["usage"]["model_requests"] == 7
    assert summary["usage"]["output_tokens"] == 2368
    # S4's task_started says `task_type` "local_agent", so the rule that refuses
    # 2.1.258's "local_bash" tasks (test_a_local_bash_task_is_not_a_subagent) must not
    # refuse this one.
    assert summary["delegation"]["subagent_count"] == 1
    assert summary["delegation"]["subagent_tokens"] == 92479
    assert summary["delegation"]["delegated_tool_calls"] == 4


@pytest.mark.integration
def test_s1_reads_the_work_the_way_a_person_would(
    replay: Callable[..., Replayed],
    store: Store,
    settled: Callable[[Store], Store],
    capsys: pytest.CaptureFixture[str],
) -> None:
    """S1's timeline is a test run, an edit and another test run, in that order.

    And `explain` reaches the provider's own bytes from the printed number: the chain
    is Evidence -> Activity -> observation payload, with no step that cannot be walked.
    """
    capture = _reduce(replay, store, settled, "S1")
    kinds = [
        str(row["activity_type"])
        for row in store.activities(capture)
        if row["activity_type"] in ("verification_run", "file_edit")
    ]
    assert kinds == ["verification_run"] * 2 + ["file_edit", "verification_run"]
    walked = _run(capsys, ["explain", capture, "model_requests"])
    assert "claude.otel.api_request" in walked
    assert '"request_id": "req_011CedKTACWDnv2fX8xeqvGP"' in walked
    assert "not a stored observation" not in walked


@pytest.mark.integration
def test_codex_usage_is_the_responses_and_never_the_turn(
    replay: Callable[..., Replayed],
    store: Store,
    settled: Callable[[Store], Store],
) -> None:
    """The summary's usage is the sum over model RESPONSES, counted from the fixture.

    The numbers on the right are read out of the recorded OTel bodies by this test, not
    out of the store, so a reducer that read the wrong attribute fails here rather than
    agreeing with itself. The turn totals are the trap: `codex.exec.turn_completed`
    reports 125350 input tokens for S1's one turn while the seven responses report
    136787 between them, and a reducer that added the turn to the responses would
    report both. The turn is its own activity and no summary metric reads it.

    `fresh_input_tokens` is the difference, not the wire value: Codex's
    input_token_count includes the cached ones (measured: last_token_usage.total_tokens
    is input plus output and never mentions cached), so the fresh part of S1 is
    136787 - 111104.
    """
    capture = _reduce(replay, store, settled, "S1", "codex")
    responses = _codex_responses("S1")
    summary = measures.summary(store, capture)

    assert len(responses) == 7, "the fixture changed; the numbers below are S1's"
    assert summary["usage"]["model_requests"] == len(responses)
    assert summary["usage"]["cache_read_tokens"] == _total(
        responses, "cached_token_count"
    )
    assert summary["usage"]["output_tokens"] == _total(responses, "output_token_count")
    assert summary["usage"]["fresh_input_tokens"] == _total(
        responses, "input_token_count"
    ) - _total(responses, "cached_token_count")
    assert summary["context"]["denominator_source"] == (
        "codex.rollout.event_msg.task_started.model_context_window"
    )

    turns = activity_fields(store, capture, "turn")
    assert len(turns) == 1
    assert turns[0]["usage_source"] == "codex.exec.turn_completed"
    assert turns[0]["total_input_tokens"] == 125350
    assert summary["usage"]["fresh_input_tokens"] == 25683


@pytest.mark.integration
def test_codex_s6_keeps_the_commands_and_the_edit_it_committed(
    replay: Callable[..., Replayed],
    store: Store,
    settled: Callable[[Store], Store],
) -> None:
    """S6 ran four commands that exited 0 and changed one file. Both survive.

    S6 is also where one tool call is named in three id spaces at once, and this is the
    assertion that catches a reducer grouping by the wrong one: eight calls are named by
    the execution id (`exec-<uuid>`) across the hooks, three OTel events and the
    rollout, while `codex.otel.tool_result` alone appears sixteen times, because a
    second copy of each is keyed by the model's own `call_<random>` id and carries no
    command, no path and no exit code.
    """
    capture = _reduce(replay, store, settled, "S6", "codex")
    calls = [
        row for kind in TOOL_KINDS for row in activity_fields(store, capture, kind)
    ]
    assert len(calls) == 8, sorted(row.get("command_norm") or "" for row in calls)

    exited = [row for row in calls if row.get("exit_code") is not None]
    assert len(exited) == 4
    assert all(row["exit_code"] == 0 for row in exited), exited
    assert all(row["success"] is True for row in exited), exited

    edits = activity_fields(store, capture, "file_edit")
    assert len(edits) == 1
    assert edits[0]["file_path"] == "pkg/calc.py"
    assert edits[0]["tool_name"] == "apply_patch"
    assert measures.summary(store, capture)["work"]["unique_files_changed"] == 1


def _codex_responses(scenario: str) -> list[dict[str, Any]]:
    """Every `codex.sse_event` response.completed attribute set, read from the fixture.

    An independent count. It walks the recorded OTLP bodies rather than asking the
    store, so it can disagree with the reducer, which is the only reason to have it.
    """
    source = CODEX_FIXTURES / scenario / "otel_logs.jsonl"
    out = []
    for line in source.read_text(encoding="utf-8").splitlines():
        body = json.loads(line)["body_json"]
        for block in body.get("resourceLogs", []):
            for scope in block.get("scopeLogs", []):
                out += [
                    attrs
                    for record in scope.get("logRecords", [])
                    if (attrs := _attrs(record)).get("event.name") == "codex.sse_event"
                    and attrs.get("event.kind") == "response.completed"
                ]
    return out


def _attrs(record: Mapping[str, Any]) -> dict[str, Any]:
    """One OTLP record's attributes, with the one-key value objects unwrapped."""
    return {
        item["key"]: next(iter(item["value"].values()))
        for item in record.get("attributes", [])
        if isinstance(item, dict) and item.get("value")
    }


def _total(responses: Sequence[Mapping[str, Any]], key: str) -> int:
    """One counter summed over the responses that carried it. Strings on the wire."""
    return sum(int(row[key]) for row in responses if row.get(key) is not None)


@pytest.mark.integration
def test_s1_verification_block_is_the_shape_the_product_exists_for(
    replay: Callable[..., Replayed],
    store: Store,
    settled: Callable[[Store], Store],
    capsys: pytest.CaptureFixture[str],
) -> None:
    """S1 ran a test, edited, ran it again. The verification block says exactly that.

    `failed_test_runs` is NULL and not 0, and the difference is the whole of W4-F3.
    S1's three runs are all `uv run pytest 2>&1 | tail -50`, the captured output of the
    first says "1 failed, 1 passed", and every surface reported the call as successful
    because the exit status of a chain is the last program's. W3-T3 stopped that status
    being read as pytest's: all three runs carry `exit_masked`, so no run states an
    outcome. W3-T3 then printed 0 for the count over what was left, which is a count
    over nothing; a 0 there says "no test run failed" about a capture where one did.
    The four numbers whose value depends on an outcome are null, their coverage is
    `partial`, and the warning says how many runs were masked and what the runs that
    were not masked came to. `agent_test_runs` is still 3, because the agent did run
    the tests three times, and that does not depend on how they ended.

    Break it by deleting the `exit_masked` guard at the top of
    `measures_intervals.failed`: `success` is on every one of these rows since W4-F3,
    so all three read as passing, `failed_test_runs` is 0 at coverage `observed` and
    the masked warning disappears.

    `edit_epochs_with_verification` is 1: one edit, closed by the run after it. It has
    no outcome in it and stays an integer.
    """
    capture = _reduce(replay, store, settled, "S1")
    summary = measures.summary(store, capture)
    block = summary["verification"]
    assert block["agent_test_runs"] == 3
    assert block["failed_test_runs"] is None
    assert block["fail_to_pass_cycles"] is None
    assert block["edits_after_last_successful_test"] is None
    assert summary["work"]["post_failure_revisits"] is None
    assert block["edit_epochs_with_verification"] == 1
    assert block["edit_epochs_without_verification"] == 0
    assert block["full_test_runs"] == 3
    evidence = {str(row["metric"]): row for row in store.evidence(capture)}
    for metric in (
        "failed_test_runs",
        "fail_to_pass_cycles",
        "edits_after_last_successful_test",
        "post_failure_revisits",
    ):
        assert evidence[metric]["coverage"] == "partial", metric
        assert (
            "3 of 3 verification runs have a masked exit status"
            in summary["warnings"][metric][0]
        ), metric
        assert (
            "Of the 0 runs whose outcome a surface stated, 0 failed"
            in summary["warnings"][metric][0]
        ), metric
    # A null is sourced from every run that was read, never from the empty set of
    # failures: `explain` has to reach the three runs a reader is being told about.
    assert len(evidence["failed_test_runs"]["source"]) == 3
    walked = _run(capsys, ["explain", capture, "fail_to_pass_cycles"])
    assert "uv run pytest" in walked
    assert "not a stored observation" not in walked


@pytest.mark.integration
def test_s2_explored_and_changed_nothing(
    replay: Callable[..., Replayed],
    store: Store,
    settled: Callable[[Store], Store],
) -> None:
    """A capture that read and searched and edited nothing: 0 changed, reading non-zero.

    The two halves matter together. `unique_files_changed` 0 is a measurement, because
    `file_paths` coverage is observed on this capture, while every exploration number is
    a positive count of work that happened. A reducer that reported the exploration
    numbers as 0 too would be describing a session that did nothing at all.
    """
    capture = _reduce(replay, store, settled, "S2")
    summary = measures.summary(store, capture)
    assert summary["work"]["unique_files_changed"] == 0
    assert summary["work"]["file_revisits"] == 0
    explored = summary["exploration"]
    assert explored["unique_files_read"] >= 1
    assert (
        explored["unique_files_read_before_first_edit"] == explored["unique_files_read"]
    )
    assert explored["search_ops"] >= 1
    assert explored["directories_traversed"] >= 1
    # Nothing was edited, so there is no denominator. Not zero, and not infinity.
    assert explored["read_to_edit_ratio"] is None
    assert explored["explored_to_final_ratio"] is None


@pytest.mark.integration
def test_a_capture_with_no_snapshots_says_unavailable_and_not_zero(
    replay: Callable[..., Replayed],
    store: Store,
    settled: Callable[[Store], Store],
) -> None:
    """S6 is stream-only: no hooks, no OTel, and no repository snapshot anywhere.

    Every metric whose input is a repository snapshot is null with coverage
    `unavailable` and a warning naming the missing observation. This is the difference
    design invariant 5 exists for: "the tree never changed" and "nothing looked at the
    tree" are different statements, and 0 would be the first one.
    """
    capture = _reduce(replay, store, settled, "S6")
    assert not [row for row in store.activities(capture)
                if row["activity_type"] == "repo_snapshot"]  # fmt: skip
    summary = measures.summary(store, capture)
    evidence = {str(row["metric"]): row for row in store.evidence(capture)}
    for metric in ("max_diff_lines", "final_diff_lines", "reversions",
                   "stable_state_work_intervals", "stable_state_total_ms",
                   "stable_state_ended_by_edit"):  # fmt: skip
        assert evidence[metric]["value"] is None, metric
        assert evidence[metric]["coverage"] == "unavailable", metric
        assert evidence[metric]["warnings"], metric
    assert summary["work"]["max_diff_lines"] is None
    assert summary["stable_state"]["stable_state_work_intervals"] is None


@pytest.mark.integration
def test_a_local_bash_task_is_not_a_subagent(
    receiver: Callable[..., Any],
    settled: Callable[[Store], Store],
) -> None:
    """Claude Code 2.1.258 announces every Bash call as a task. It starts no subagent.

    Five `task_started` messages of the shape 2.1.258 emits for a Bash call, each with a
    distinct task_id and `task_type` "local_bash". Before this rule they became five
    subagent activities on a session that spawned none, and a comparison of delegation
    between two runtime versions would have been reading a version bump. The
    counter-example is `test_s4_subagent_has_attributed_tokens`: S4 on 2.1.257 announces
    its one real subagent with `task_type` "local_agent" and still counts.

    `subagent_count` is 0 and not null: the stream is a surface on which a subagent IS
    observable (providers/claude.py CAPABILITIES), so "none was spawned" is something
    this capture could say. A capture with no such surface reports null instead, which
    is what `_honest` is for.
    """
    live = receiver()
    for index in range(5):
        live.post(
            "/v1/stream/claude",
            json.dumps(
                {
                    "type": "system",
                    "subtype": "task_started",
                    "task_id": f"b{index}xy339v",
                    "task_type": "local_bash",
                    "is_backgrounded": False,
                    "tool_use_id": f"toolu_{index}",
                    "session_id": "local-bash-only",
                    "uuid": f"uuid-{index}",
                }
            ).encode(),
            capture="LOCALBASH",
        )
    live.drain()
    live.store.rebuild("LOCALBASH")
    settled(live.store)
    assert not [row for row in live.store.activities("LOCALBASH")
                if row["activity_type"] == "subagent"]  # fmt: skip
    delegation = measures.summary(live.store, "LOCALBASH")["delegation"]
    assert delegation["subagent_count"] == 0
    assert delegation["subagent_tokens"] is None


@pytest.mark.integration
def test_a_masked_exit_status_is_unknown_and_not_a_pass(tmp_path: Path) -> None:
    """A run piped into `tail` is counted, and its outcome is not. W3-T3, W4-F3.

    The scripted agent's `--pipe` mode makes two test runs. The first is
    `uv run pytest 2>&1 | tail -50` and its tool_result carries is_error FALSE while
    the output says the tests failed, which is what all five of W2-E05's re-run
    sessions did; the second is `uv run pytest` with nothing after it and really
    reports a failure. So the capture holds one run whose result nobody observed and
    one whose result is known.

    `agent_test_runs` is 2, because the agent ran the tests twice and that is not a
    statement about how they ended. `failed_test_runs` is NULL: one of the two states
    no outcome, so the honest answer is not 1 either. W3-T3 printed 1 here, and 1 is
    the count of the failures somebody happened to see, which reads as the count of the
    failures. The warning carries the two numbers the null no longer prints.

    The timeline says `ok, check masked` for the piped run: `ok` because the tool call
    really did exit 0, and the rest because that 0 is `tail`'s.

    Break it by deleting the `exit_masked` guard at the top of
    `measures_intervals.failed`: the piped run reads as passing, `failed_test_runs`
    comes back as 1 at coverage `observed` and the warning disappears.
    """
    store, capture = launched(tmp_path, "--pipe")
    summary = measures.summary(store, capture)
    evidence = {str(row["metric"]): row for row in store.evidence(capture)}
    runs = activity_fields(store, capture, "verification_run")

    assert summary["verification"]["agent_test_runs"] == 2
    assert summary["verification"]["failed_test_runs"] is None
    assert [row.get("exit_masked") for row in runs] == [True, None]
    # The piped call's own success, which the stream states and W4-F3 keeps: the shell
    # exited 0 because `tail` did. `success` False on the second is pytest's own.
    assert [row.get("success") for row in runs] == [True, False]
    assert evidence["failed_test_runs"]["coverage"] == "partial"
    assert (
        "1 of 2 verification runs has a masked exit status"
        in summary["warnings"]["failed_test_runs"][0]
    )
    assert (
        "Of the 1 run whose outcome a surface stated, 1 failed"
        in summary["warnings"]["failed_test_runs"][0]
    )
    printed = telltale_cli("timeline", capture, home=store.path.parent)
    piped = [line for line in printed.splitlines() if "| tail -50" in line]
    assert len(piped) == 1, printed
    assert piped[0].split()[-4:] == ["ok,", "check", "masked", "derived"], piped[0]


@pytest.mark.integration
def test_a_refused_read_is_not_a_file_read(tmp_path: Path) -> None:
    """A file tool the provider refused opened no file, so nothing counts it. W3-T3.

    The scripted agent's `--deny-read` mode makes no ordinary Read call and one Read
    that the provider refuses, in a repository that HAS a readable file, so 0 files
    read is a statement about the session and not about an empty directory. W3-T0 made
    this true for a refused test command and left the four other types alone, having no
    capture where it mattered: every refusal it had was a Bash call.

    `unique_files_read` is 0, `directories_traversed` is 0, `read_to_edit_ratio` is
    0.0 over the one edit, and `refused_tool_calls` is 1. The row is still there with
    its tool_name, its path and `outcome` refused, because what the agent asked for is
    a fact worth keeping; what it is not is a file that was read.

    Break it by restoring `if category in VERIFICATION and not refused` in
    `activities_tools._tool_type` and dropping the `if refused` branch: the refused Read
    becomes a file_read, unique_files_read goes to 1 and the ratio to 1.0.
    """
    store, capture = launched(tmp_path, "--deny-read")
    summary = measures.summary(store, capture)
    refused = [
        row
        for row in activity_fields(store, capture, "tool_call")
        if row["tool_name"] == "Read"
    ]

    assert summary["exploration"]["unique_files_read"] == 0
    assert summary["exploration"]["unique_files_read_before_first_edit"] == 0
    assert summary["exploration"]["directories_traversed"] == 0
    assert summary["exploration"]["read_to_edit_ratio"] == 0.0
    assert summary["work"]["refused_tool_calls"] == 1
    assert not activity_fields(store, capture, "file_read")
    assert len(refused) == 1
    assert refused[0]["outcome"] == "refused"
    assert refused[0]["executed"] is False
    assert refused[0]["file_path"] == "answer.txt"


@pytest.mark.integration
def test_codex_s1_counts_the_env_prefixed_test_runs(
    replay: Callable[..., Replayed],
    store: Store,
    settled: Callable[[Store], Store],
) -> None:
    """Three pytest runs, two of them behind an environment assignment.

    `UV_CACHE_DIR=/tmp/... uv run pytest` used to classify as `git`, because the normal
    form dropped the `=` and classify() then found no category for `UV_CACHE_DIR`, fell
    through to the next segment and read the `git status` at the end of the pipeline.
    The three runs are rollout.jsonl CommandExecution items exec-df395f88 (`uv run
    pytest`), exec-7984baec and exec-62b47475 (both env-prefixed), so this is 3 and not
    the 2 an earlier reading of the fixture expected.

    exec-7984baec carries exit code 1 and status "failed" while
    `codex.otel.tool_result.success` is true, so `failed_test_runs` reads the exit
    status: 1 failure, and one fail-to-pass cycle with the passing run after the edit.

    This is also the capture that says W4-F3 did not simply null everything out. None
    of the three chains is masked, every one of them states an outcome, so all four of
    the numbers whose value now depends on that stay integers and their coverage stays
    `observed`. It is the only golden fixture with a non-zero failure count and no
    masked run, which is why the assertion is here and not on claude/S1, whose three
    runs all pipe pytest into `tail`.
    """
    capture = _reduce(replay, store, settled, "S1", "codex")
    runs = activity_fields(store, capture, "verification_run")
    assert sorted(str(row["command_norm"]) for row in runs) == [
        "UV_CACHE_DIR= uv run pytest",
        "UV_CACHE_DIR= uv run pytest",
        "uv run pytest",
    ]
    assert [row.get("exit_masked") for row in runs] == [None] * 3
    summary = measures.summary(store, capture)
    block = summary["verification"]
    assert block["agent_test_runs"] == 3
    assert block["failed_test_runs"] == 1
    assert block["fail_to_pass_cycles"] == 1
    assert block["edits_after_last_successful_test"] == 0
    assert summary["work"]["post_failure_revisits"] == 1
    evidence = {str(row["metric"]): row for row in store.evidence(capture)}
    assert evidence["failed_test_runs"]["coverage"] == "observed"
    assert evidence["fail_to_pass_cycles"]["coverage"] == "observed"
    assert "failed_test_runs" not in summary["warnings"]
