"""From recorded bytes to a session summary, through the real commands.

Every test here replays one of E01's captured Claude Code sessions over HTTP into a
real receiver and a real store, runs the activity reducer, then invokes `telltale`.
Nothing is stubbed and nothing calls a reducer's internals: what is asserted is what a
person running the command would see.

The goldens are `fixtures/golden/claude/<scenario>/{show.json,timeline.txt}`, and they
are the output of `telltale show` and `telltale timeline` on exactly this pipeline.
They are regenerated by running this suite with TELLTALE_GOLDEN=write, the same code
path as the comparison, so no golden can come from a route the test does not take.
Every number in them is checked by hand against the fixture in docs/log/W1-T2.md.

One normalization, named. `reducer_version` is the hash of the reducer's own source,
so it changes with every edit to it and would make the goldens a diff of themselves; it
is replaced by a placeholder. Nothing else is touched: the capture
id, the timestamps, the token counts and the row order are compared byte for byte,
which is what makes a golden worth having.

Why these three scenarios. S1 is the shape the product exists for: a failing test, an
edit, a passing test. S4 is the only capture with a subagent, which is the one place
where token attribution can double-count. S7 is the only capture with compaction, and it
compacted four times on three surfaces with one failure, which is where the correlation
rules earn their keep.
"""

from __future__ import annotations

import json
import os
from pathlib import Path
from typing import TYPE_CHECKING, Any

import pytest

from telltale import cli, measures

if TYPE_CHECKING:
    from collections.abc import Callable, Iterable, Mapping, Sequence

    from conftest import Replayed

    from telltale.store import Store

GOLDEN = Path(__file__).resolve().parents[2] / "fixtures" / "golden" / "claude"
SCENARIOS = ("S1", "S4", "S7")

# The reducer version is a hash of the source, so it is different in every commit that
# touches activities.py. The goldens carry this instead, and the test that a version is
# recorded at all is `test_show_matches_golden` failing when the key disappears.
STRIPPED = "<reducer_version>"

# Set to "write" to regenerate the goldens instead of comparing against them. The
# comparison and the regeneration share this one function, so a golden is always the
# output of the command the test runs.
WRITE = os.environ.get("TELLTALE_GOLDEN") == "write"


def _reduce(
    replay: Callable[..., Replayed],
    store: Store,
    settled: Callable[[Store], Store],
    scenario: str,
) -> str:
    """Replay one scenario, run every reducer, close the store, return the capture id.

    The close is the barrier: `Store._serve_once` takes a job off the queue before it
    opens the transaction, so an empty queue is not proof that the writer has finished
    (conftest's `settled` says why at length). Reading before it would ask the question
    of fewer rows than were written.
    """
    replayed = replay(scenario)
    store.rebuild(replayed.capture)
    settled(store)
    return replayed.capture


def _golden(path: Path, actual: str) -> None:
    if WRITE:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(actual, encoding="utf-8")
    assert path.exists(), f"{path} is missing; regenerate with TELLTALE_GOLDEN=write"
    assert actual == path.read_text(encoding="utf-8")


def _run(capsys: pytest.CaptureFixture[str], argv: Sequence[str]) -> str:
    assert cli.main(list(argv)) == 0
    return capsys.readouterr().out


def _stripped(printed: str) -> str:
    summary = json.loads(printed)
    assert summary["reducer_version"].startswith("act-"), summary["reducer_version"]
    summary["reducer_version"] = STRIPPED
    return json.dumps(summary, indent=2, ensure_ascii=False) + "\n"


def _rows(store: Store, capture: str) -> list[tuple[Any, ...]]:
    """Activity and evidence rows as comparable tuples, ids and all."""
    tables = (store.activities(capture), store.evidence(capture))
    return [_row(row) for table in tables for row in table]


def _row(row: Mapping[str, Any]) -> tuple[Any, ...]:
    return tuple(
        (key, json.dumps(value, sort_keys=True)) for key, value in sorted(row.items())
    )


def _referenced(store: Store, capture: str) -> Iterable[tuple[str, str]]:
    """Every id this capture's derived rows point at, with where it was found."""
    for row in store.activities(capture):
        for name, ids in dict(row["provenance"]).items():
            for one in ids:
                yield f"{row['activity_id']}.provenance.{name}", one
        for one in dict(row["fields"]).get("delegated_tool_calls") or []:
            yield f"{row['activity_id']}.delegated_tool_calls", one
    for row in store.evidence(capture):
        for one in row["source"]:
            yield f"{row['evidence_id']}.source", one


def _fields(store: Store, capture: str, kind: str) -> list[Mapping[str, Any]]:
    return [
        dict(row["fields"])
        for row in store.activities(capture)
        if row["activity_type"] == kind
    ]


@pytest.mark.integration
@pytest.mark.parametrize("scenario", SCENARIOS)
def test_show_matches_golden(
    scenario: str,
    replay: Callable[..., Replayed],
    store: Store,
    settled: Callable[[Store], Store],
    capsys: pytest.CaptureFixture[str],
) -> None:
    """`telltale show` prints Appendix B, coverage first and the diagnostics last."""
    capture = _reduce(replay, store, settled, scenario)
    printed = _stripped(_run(capsys, ["show", capture]))
    keys = list(json.loads(printed))
    assert keys[0] == "coverage", keys
    assert keys[-1] == "diagnostics", keys
    _golden(GOLDEN / scenario / "show.json", printed)


@pytest.mark.integration
@pytest.mark.parametrize("scenario", SCENARIOS)
def test_timeline_matches_golden(
    scenario: str,
    replay: Callable[..., Replayed],
    store: Store,
    settled: Callable[[Store], Store],
    capsys: pytest.CaptureFixture[str],
) -> None:
    """`telltale timeline` prints one row per activity, in the order they started."""
    capture = _reduce(replay, store, settled, scenario)
    _golden(GOLDEN / scenario / "timeline.txt", _run(capsys, ["timeline", capture]))


@pytest.mark.integration
@pytest.mark.parametrize("scenario", SCENARIOS)
def test_rebuild_is_repeatable(
    scenario: str,
    replay: Callable[..., Replayed],
    store: Store,
    settled: Callable[[Store], Store],
) -> None:
    """Two rebuilds of one capture produce byte-identical activity and evidence rows.

    Break it by giving an activity a `ulid()` id or an Evidence a wall-clock
    `created_at` and this fails on every row, which is the point: a derived table that
    changes when nothing changed cannot be compared across captures or across time.
    """
    replayed = replay(scenario)
    store.rebuild(replayed.capture)
    before = _rows(store, replayed.capture)
    store.rebuild(replayed.capture)
    settled(store)
    after = _rows(store, replayed.capture)
    assert before, "the reducer wrote nothing at all"
    assert before == after


@pytest.mark.integration
@pytest.mark.parametrize("scenario", SCENARIOS)
def test_every_source_and_provenance_id_resolves(
    scenario: str,
    replay: Callable[..., Replayed],
    store: Store,
    settled: Callable[[Store], Store],
) -> None:
    """No derived row points at an id that is not in this capture.

    An unresolvable id is the failure mode `explain` cannot report around: the chain
    from a number to the bytes behind it is only as good as its weakest link, and a
    reducer that invents an id breaks it silently.
    """
    capture = _reduce(replay, store, settled, scenario)
    known = {str(row["observation_id"]) for row in store.observations(capture)}
    known |= {str(row["activity_id"]) for row in store.activities(capture)}
    seen = _referenced(store, capture)
    dangling = [(where, one) for where, one in seen if one not in known]
    assert not dangling, dangling
    assert known, "no observations were stored"


@pytest.mark.integration
def test_s7_compactions_carry_pre_and_post_tokens_on_three_surfaces(
    replay: Callable[..., Replayed],
    store: Store,
    settled: Callable[[Store], Store],
) -> None:
    """S7 compacted four times. Three succeeded, and all three were seen three ways.

    The fourth is the one that matters most: E01 measured a compaction that failed with
    `too_few_groups` and reported no post_tokens and no stream boundary, so the summary
    reports partial coverage for post_compaction_tokens rather than a smaller total that
    looks complete.
    """
    capture = _reduce(replay, store, settled, "S7")
    found = _fields(store, capture, "compaction")
    rows = sorted(found, key=lambda one: int(one["compaction_index"]))
    assert [row["pre_tokens"] for row in rows] == [34181, 35113, 38398, 42366]
    assert [row.get("post_tokens") for row in rows] == [None, 3909, 8138, 5193]
    assert [row["success"] for row in rows] == [False, True, True, True]
    assert rows[0]["surfaces"] == ["hook", "otel_logs"]
    for row in rows[1:]:
        assert row["surfaces"] == ["hook", "otel_logs", "stream"]
    summary = measures.summary(store, capture)
    assert summary["context"]["compactions"] == 4
    assert summary["context"]["pre_compaction_tokens"] == 34181 + 35113 + 38398 + 42366
    assert summary["context"]["post_compaction_tokens"] == 3909 + 8138 + 5193
    assert summary["warnings"]["post_compaction_tokens"]


@pytest.mark.integration
def test_s4_subagent_has_attributed_tokens(
    replay: Callable[..., Replayed],
    store: Store,
    settled: Callable[[Store], Store],
) -> None:
    """S4 delegated once, and the child's tokens are attributed without being doubled.

    `attributed_total_tokens` is the sum over the five api_requests whose query_source
    names this agent, and those five are already inside the capture's own usage totals.
    `provider_total_tokens` is what claude_code.subagent_completed reports, and the two
    are 92479 and 20093: different quantities, so they are stored under different names
    and neither is added to the other (spec 13.6).
    """
    capture = _reduce(replay, store, settled, "S4")
    rows = _fields(store, capture, "subagent")
    assert len(rows) == 1
    child = rows[0]
    assert child["agent_id"] == "a98af9d1d9cc27170"
    assert child["agent_type"] == "Explore"
    assert child["attributed_requests"] == 5
    assert child["attributed_total_tokens"] == 92479
    assert child["provider_total_tokens"] == 20093
    assert len(child["delegated_tool_calls"]) == 4
    # The capture's own totals count every request once, subagent requests included.
    summary = measures.summary(store, capture)
    assert summary["usage"]["model_requests"] == 7
    assert summary["usage"]["output_tokens"] == 2368


@pytest.mark.integration
def test_s1_reads_the_work_the_way_a_person_would(
    replay: Callable[..., Replayed],
    store: Store,
    settled: Callable[[Store], Store],
    capsys: pytest.CaptureFixture[str],
) -> None:
    """S1's timeline is a test run, an edit and another test run, in that order.

    And `explain` reaches the provider's own bytes from the printed number: the chain
    is Evidence -> Activity -> observation payload, with no step that cannot be walked.
    """
    capture = _reduce(replay, store, settled, "S1")
    kinds = [
        str(row["activity_type"])
        for row in store.activities(capture)
        if row["activity_type"] in ("verification_run", "file_edit")
    ]
    assert kinds == ["verification_run"] * 2 + ["file_edit", "verification_run"]
    walked = _run(capsys, ["explain", capture, "model_requests"])
    assert "claude.otel.api_request" in walked
    assert '"request_id": "req_011CedKTACWDnv2fX8xeqvGP"' in walked
    assert "not a stored observation" not in walked
